FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install openjdk-21-jdk -y
RUN apt-get install curl -y

COPY config-server/target/config-server.jar home/app.jar

WORKDIR /home

EXPOSE 8888
ENTRYPOINT ["java","-jar","app.jar"]
#CMD /bin/bash