version: '3.7'
services:
  config-server:
    image: ${GROUP_ID}/config-server:1.0
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
      - "../config-server-repository:/home/config-server-repository"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888 -Xms128m -Xmx256m"
      - "SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH-LOCATIONS=file:///home/config-server-repository"
      - "LOGGING_LEVEL_ROOT=info"
    networks:
      - ${GLOBAL_NETWORK:-kafka}