version: '3.7'
services:
  elastic-query-service:
    image: ${GROUP_ID}/elastic-query-service:1.0
    container_name: elastic-query-service
    ports:
      - "8183:8183"
    volumes:
      - "./docker-logs:/workspace/elastic-query-service/logs"
      - "./check-config-server-started.sh:/home/check-config-server-started.sh"
    user: root
    entrypoint: [ "/home/check-config-server-started.sh" ]
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888"
      - "ELASTIC-CONFIG_CONNECTION-URL=elastic-1:9200"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    restart: on-failure