version: '3.7'
services:
  config-server:
    image: ${GROUP_ID}/config-server:1.0
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8888 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
  twitter-to-kafka-service:
    image: ${GROUP_ID}/twitter.to.kafka.service:${SERVICE_VERSION:-latest}
    container_name: twitter-to-kafka-service
    depends_on:
      - config-server
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
#      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
#    user: root
#    entrypoint: ["check-config-server-started.sh"]
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    restart: on-failure