server:
  port: 8888

logging:
  level:
    ROOT: info
    org.spring.framework.cloud.config: DEBUG

spring:
  profiles:
#    enable to read configuration from disk
    active: native
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
#          search-locations: ${SEARCH_LOCATIONS}
          search-locations: file://${user.home}/IdeaProjects/microservices-demo/config-server-repository
#        git:
#          uri: file://${user.home}/IdeaProjects/microservices-demo/config-server-repository